"use client";

import { FormEvent, useState } from "react";
import { ArrowRight, MagnifyingGlass, ShieldCheck } from "@phosphor-icons/react";
import { Button } from "@/components/ui/button";
import { Field, TextInput } from "@/components/ui/field";
import { Panel, PanelBody } from "@/components/ui/card";
import { ErrorState } from "@/components/ui/states";
import { StatusBadge } from "@/components/ui/status-badge";
import { api, type PublicCertificate } from "@/lib/api-client";

export default function PublicVerifyPage() {
  const [value, setValue] = useState(""); const [result, setResult] = useState<PublicCertificate | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(null); setResult(null); try { setResult(await api.verifyCertificate(value.startsWith("EVM-CERT-") ? { certificateNumber: value } : { token: value })); } catch (cause) { setError(cause instanceof Error ? cause.message : "Certificate could not be verified"); } finally { setLoading(false); } }
  return <><header className="public-header"><div className="brand-lockup"><span className="brand-mark">eV</span><span><span className="brand-name">e-VerifyMet</span><span className="brand-subtitle">Public verification</span></span></div><span className="status-badge status-info"><ShieldCheck size={14} /> No sign in required</span></header><main className="public-main"><Panel className="verify-card"><PanelBody><div className="eyebrow">Certificate authenticity</div><h1 className="page-heading">Check a certificate.</h1><p className="page-lede">Enter the QR token or certificate number to see its current public status.</p><form className="verify-form" onSubmit={submit}><Field label="QR token or certificate number" hint="Use the value printed on the certificate or returned by its QR code."><TextInput required value={value} onChange={(event) => setValue(event.target.value)} placeholder="Enter verification value" /></Field><Button type="submit" disabled={loading} icon={<MagnifyingGlass size={18} />}>{loading ? "Checking…" : "Verify certificate"}</Button></form>{error ? <div style={{ marginTop: 18 }}><ErrorState message={error} /></div> : null}{result ? <div className="verify-result" aria-live="polite"><div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12 }}><h2 className="section-heading">Verification result</h2><StatusBadge value={result.valid ? "Valid" : result.status} tone={result.valid ? "success" : "danger"} /></div><div className="verify-result-grid"><div><span className="result-label">Certificate</span><span className="result-value">{result.certificateNumber}</span></div><div><span className="result-label">Status</span><span className="result-value">{result.status.replaceAll("_", " ")}</span></div><div><span className="result-label">Instrument</span><span className="result-value">{result.instrument.instrumentType}</span></div><div><span className="result-label">Public ID</span><span className="result-value">{result.instrument.publicInstrumentId}</span></div></div><a href="/verify" style={{ display: "inline-flex", alignItems: "center", gap: 6, marginTop: 20, color: "var(--accent-strong)", fontSize: 13, fontWeight: 700 }}>Verify another <ArrowRight size={15} /></a></div> : null}</PanelBody></Panel></main></>;
}